//! Calendars (`calendars`): get, insert, update, patch, delete, clear,
//! transfer ownership.
//!
//! A calendar is the container of events, addressed by its id (an email
//! address, or the alias `primary` for the authenticated user's own
//! calendar). The metadata a given user layers on top of it lives on
//! their [`crate::v3::rest::calendar_list`] entry instead.
//!
//! <https://developers.google.com/workspace/calendar/api/v3/reference/calendars>

use alloc::{string::String, vec::Vec};

use serde::{Deserialize, Serialize};

pub mod clear;
pub mod delete;
pub mod get;
pub mod insert;
pub mod patch;
pub mod transfer_ownership;
pub mod update;

/// A calendar and the properties shared by everyone who accesses it.
#[derive(Debug, Clone, Default, Deserialize, Serialize, Eq, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct GcalCalendar {
    /// Type of the resource, always `calendar#calendar`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub kind: Option<String>,
    /// ETag of the resource.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub etag: Option<String>,
    /// Identifier of the calendar.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Title of the calendar.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub summary: Option<String>,
    /// Description of the calendar.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Geographic location of the calendar as free-form text.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub location: Option<String>,
    /// Time zone of the calendar, as an IANA Time Zone Database name
    /// such as `Europe/Zurich`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub time_zone: Option<String>,
    /// Email of the owner of the calendar, set on secondary calendars
    /// only.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub data_owner: Option<String>,
    /// Whether the calendar automatically accepts invitations, valid
    /// for resource calendars only.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub auto_accept_invitations: Option<bool>,
    /// Which types of conferences are allowed on this calendar.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub conference_properties: Option<GcalConferenceProperties>,
    /// Event labels defined on this calendar. Sending it on a write
    /// replaces the existing labels as a whole.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub label_properties: Option<GcalLabelProperties>,
}

/// The conferencing capabilities of a calendar.
#[derive(Debug, Clone, Default, Deserialize, Serialize, Eq, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct GcalConferenceProperties {
    /// The types of conference solutions supported for this calendar.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub allowed_conference_solution_types: Vec<GcalConferenceSolutionType>,
}

/// A conference provider backing a conference on an event.
#[derive(Debug, Clone, Copy, Deserialize, Serialize, Eq, PartialEq)]
#[serde(rename_all = "camelCase")]
pub enum GcalConferenceSolutionType {
    /// Hangouts for consumers, deprecated: existing events may still
    /// carry it but new conferences cannot be created with it.
    EventHangout,
    /// Classic Hangouts for Google Workspace users, deprecated: existing
    /// events may still carry it but new conferences cannot be created
    /// with it.
    EventNamedHangout,
    /// Google Meet.
    HangoutsMeet,
    /// A third-party conference provider, added on.
    AddOn,
}

/// The event labels defined on a calendar.
#[derive(Debug, Clone, Default, Deserialize, Serialize, Eq, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct GcalLabelProperties {
    /// The event labels defined on this calendar. On a write it
    /// replaces the existing list, so extend the list to add one and
    /// shrink it to remove one.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub event_labels: Vec<GcalEventLabel>,
}

/// A named colour an event of the calendar can be tagged with.
#[derive(Debug, Clone, Default, Deserialize, Serialize, Eq, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct GcalEventLabel {
    /// The id of the label, generated by the server when a new label
    /// omits it, required when updating one.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Name of the label, at most 50 characters.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Background colour of the label in hexadecimal format, such as
    /// `#039be5`. Required.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub background_color: Option<String>,
}
