//! Events (`events`): list, get, insert, update, patch, delete,
//! import, instances, move, quick add, watch.
//!
//! The central resource of the API: an event on one calendar, either a
//! single occurrence, a recurring series described by its RFC 5545
//! recurrence rules, or one instance of such a series.
//!
//! <https://developers.google.com/workspace/calendar/api/v3/reference/events>

use alloc::{collections::BTreeMap, string::String, vec::Vec};

use serde::{Deserialize, Serialize};
use serde_json::Value;

use crate::v3::rest::{acl::GcalAccessRole, calendars::GcalConferenceSolutionType};

pub mod delete;
pub mod get;
pub mod import;
pub mod insert;
pub mod instances;
pub mod list;
pub mod r#move;
pub mod patch;
pub mod quick_add;
pub mod update;
pub mod watch;

/// The events of a calendar, one page of the listing.
#[derive(Debug, Clone, Default, Deserialize, Serialize, Eq, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct GcalEvents {
    /// Type of the collection, always `calendar#events`.
    #[serde(default)]
    pub kind: Option<String>,
    /// ETag of the collection.
    #[serde(default)]
    pub etag: Option<String>,
    /// Title of the calendar the events belong to, read-only.
    #[serde(default)]
    pub summary: Option<String>,
    /// Description of the calendar the events belong to, read-only.
    #[serde(default)]
    pub description: Option<String>,
    /// Time zone of the calendar the events belong to, read-only.
    #[serde(default)]
    pub time_zone: Option<String>,
    /// Last modification time of the calendar, as an RFC 3339
    /// timestamp, read-only.
    #[serde(default)]
    pub updated: Option<String>,
    /// The access role the authenticated user has on the calendar,
    /// read-only.
    #[serde(default)]
    pub access_role: Option<GcalAccessRole>,
    /// The default reminders of the calendar, applying to every event
    /// that does not override them.
    #[serde(default)]
    pub default_reminders: Vec<GcalEventReminder>,
    /// The events of the current page.
    #[serde(default)]
    pub items: Vec<GcalEvent>,
    /// The token retrieving the next page, absent on the last page.
    #[serde(default)]
    pub next_page_token: Option<String>,
    /// The token retrieving only what changed since this listing,
    /// present on the last page only.
    #[serde(default)]
    pub next_sync_token: Option<String>,
}

/// An event on a calendar.
#[derive(Debug, Clone, Default, Deserialize, Serialize, Eq, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct GcalEvent {
    /// Type of the resource, always `calendar#event`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub kind: Option<String>,
    /// ETag of the resource.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub etag: Option<String>,
    /// Opaque identifier of the event, generated by the server when a
    /// new event omits it.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Status of the event.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub status: Option<GcalEventStatus>,
    /// Absolute link to the event in the Calendar web UI, read-only.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub html_link: Option<String>,
    /// Creation time of the event, as an RFC 3339 timestamp, read-only.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub created: Option<String>,
    /// Last modification time of the event data, as an RFC 3339
    /// timestamp, read-only. Changing reminders does not bump it.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub updated: Option<String>,
    /// Title of the event.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub summary: Option<String>,
    /// Description of the event, which may contain HTML.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Geographic location of the event as free-form text.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub location: Option<String>,
    /// Index-based colour of the event, referring to an entry in the
    /// `event` palette of [`crate::v3::rest::colors`].
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub color_id: Option<String>,
    /// The event label assigned to the event, referring to an entry in
    /// the label properties of the calendar. Writing it requires the
    /// `eventLabelVersion` parameter, and it supersedes the index-based
    /// colour id.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub event_label_id: Option<String>,
    /// The creator of the event, read-only.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub creator: Option<GcalEventPerson>,
    /// The organizer of the event, which may be a calendar rather than
    /// a person.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub organizer: Option<GcalEventPerson>,
    /// The inclusive start of the event, or of its first instance for a
    /// recurring event.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub start: Option<GcalEventDateTime>,
    /// The exclusive end of the event, or of its first instance for a
    /// recurring event.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub end: Option<GcalEventDateTime>,
    /// Whether the end time is in fact unspecified, an end time still
    /// being provided for compatibility.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub end_time_unspecified: Option<bool>,
    /// The RFC 5545 `RRULE`, `EXRULE`, `RDATE` and `EXDATE` lines of a
    /// recurring event. `DTSTART` and `DTEND` are carried by the start
    /// and end fields instead, and are not allowed here.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub recurrence: Vec<String>,
    /// For an instance of a recurring event, the id of the series it
    /// belongs to.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub recurring_event_id: Option<String>,
    /// For an instance of a recurring event, the time at which it would
    /// have started according to the recurrence rules of the series.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub original_start_time: Option<GcalEventDateTime>,
    /// Whether the event blocks time on the calendar.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub transparency: Option<GcalEventTransparency>,
    /// Visibility of the event.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub visibility: Option<GcalEventVisibility>,
    /// The RFC 5545 unique identifier of the event, shared by every
    /// instance of a recurring series and stable across calendaring
    /// systems. Required when importing an event.
    #[serde(default, rename = "iCalUID", skip_serializing_if = "Option::is_none")]
    pub ical_uid: Option<String>,
    /// Revision number of the event, as per iCalendar.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub sequence: Option<u32>,
    /// The attendees of the event.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub attendees: Vec<GcalEventAttendee>,
    /// Whether attendees may have been left out of this
    /// representation, because of the `maxAttendees` parameter or of a
    /// restriction on the request.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub attendees_omitted: Option<bool>,
    /// Extended properties of the event, private to this copy or shared
    /// with the copies on the attendees' calendars.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extended_properties: Option<GcalEventExtendedProperties>,
    /// Absolute link to the Google Hangout of the event, read-only.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub hangout_link: Option<String>,
    /// The conference attached to the event, such as a Google Meet.
    /// Writing it requires the `conferenceDataVersion` parameter.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub conference_data: Option<GcalConferenceData>,
    /// A gadget extending the event. Gadgets are deprecated; the field
    /// now only carries birthday calendar metadata.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub gadget: Option<GcalEventGadget>,
    /// Whether anyone can invite themselves to the event, deprecated.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub anyone_can_add_self: Option<bool>,
    /// Whether attendees other than the organizer can invite others.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub guests_can_invite_others: Option<bool>,
    /// Whether attendees other than the organizer can modify the event.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub guests_can_modify: Option<bool>,
    /// Whether attendees other than the organizer can see who else is
    /// attending.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub guests_can_see_other_guests: Option<bool>,
    /// Whether the propagation of the event to the attendees is
    /// disabled. Immutable.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub private_copy: Option<bool>,
    /// Whether this is a locked copy of the event, on which the summary,
    /// description, location, start, end and recurrence cannot change.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub locked: Option<bool>,
    /// The reminders of the authenticated user for this event.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reminders: Option<GcalEventReminders>,
    /// The resource the event was created from, such as a web page or
    /// an email message.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub source: Option<GcalEventSource>,
    /// Working location data, used when the event type is
    /// [`GcalEventType::WorkingLocation`].
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub working_location_properties: Option<GcalEventWorkingLocationProperties>,
    /// Out of office data, used when the event type is
    /// [`GcalEventType::OutOfOffice`].
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub out_of_office_properties: Option<GcalEventOutOfOfficeProperties>,
    /// Focus time data, used when the event type is
    /// [`GcalEventType::FocusTime`].
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub focus_time_properties: Option<GcalEventFocusTimeProperties>,
    /// Birthday or special event data, used when the event type is
    /// [`GcalEventType::Birthday`]. Immutable.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub birthday_properties: Option<GcalEventBirthdayProperties>,
    /// The files attached to the event, at most 25. Writing them
    /// requires the `supportsAttachments` parameter.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub attachments: Vec<GcalEventAttachment>,
    /// Specific type of the event, immutable once created.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub event_type: Option<GcalEventType>,
}

/// One end of an event, either a date for an all-day event or a
/// timestamp for a timed one.
#[derive(Debug, Clone, Default, Deserialize, Serialize, Eq, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct GcalEventDateTime {
    /// The date, formatted `yyyy-mm-dd`, for an all-day event.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub date: Option<String>,
    /// The combined date and time, as an RFC 3339 timestamp. A UTC
    /// offset is required unless the time zone is given separately.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub date_time: Option<String>,
    /// The time zone the time is expressed in, as an IANA Time Zone
    /// Database name. Required on a recurring event, where it anchors
    /// the expansion of the recurrence.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub time_zone: Option<String>,
}

impl GcalEventDateTime {
    /// Whether the boundary is a timed one carrying no time zone.
    ///
    /// A recurring event cannot have such a boundary: its recurrence is
    /// expanded in the time zone of its start, and the UTC offset a
    /// timestamp carries does not name one. An all-day boundary, dated
    /// rather than timed, needs no time zone.
    pub fn is_timed_without_time_zone(&self) -> bool {
        self.date_time.is_some() && self.time_zone.is_none()
    }
}

/// The creator or the organizer of an event.
#[derive(Debug, Clone, Default, Deserialize, Serialize, Eq, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct GcalEventPerson {
    /// The profile id of the person.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// The email address of the person.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    /// The name of the person.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
    /// Whether the person is the calendar this copy of the event
    /// appears on, read-only. Serialized as `self`.
    #[serde(default, rename = "self", skip_serializing_if = "Option::is_none")]
    pub is_self: Option<bool>,
}

/// One attendee of an event.
#[derive(Debug, Clone, Default, Deserialize, Serialize, Eq, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct GcalEventAttendee {
    /// The profile id of the attendee.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// The email address of the attendee. Required when adding one.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    /// The name of the attendee.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
    /// Whether the attendee is the organizer of the event, read-only.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub organizer: Option<bool>,
    /// Whether the attendee is the calendar this copy of the event
    /// appears on, read-only. Serialized as `self`.
    #[serde(default, rename = "self", skip_serializing_if = "Option::is_none")]
    pub is_self: Option<bool>,
    /// Whether the attendee is a resource, such as a room. Can only be
    /// set when the attendee is first added.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub resource: Option<bool>,
    /// Whether the attendance of the attendee is optional.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub optional: Option<bool>,
    /// The response of the attendee to the invitation.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub response_status: Option<GcalEventAttendeeResponseStatus>,
    /// The response comment of the attendee.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub comment: Option<String>,
    /// The number of guests the attendee brings along.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub additional_guests: Option<u32>,
    /// The asynchronous operation ongoing for this attendee, such as
    /// the expansion of a large group, read-only. Absent when none is.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub async_operation: Option<GcalEventAttendeeAsyncOperation>,
}

/// The reminders of the authenticated user for one event.
#[derive(Debug, Clone, Default, Deserialize, Serialize, Eq, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct GcalEventReminders {
    /// Whether the default reminders of the calendar apply.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub use_default: Option<bool>,
    /// The reminders specific to this event, at most five. An empty
    /// list with the defaults turned off means no reminder at all.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub overrides: Vec<GcalEventReminder>,
}

/// One reminder, as a delivery method and a lead time.
#[derive(Debug, Clone, Default, Deserialize, Serialize, Eq, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct GcalEventReminder {
    /// How the reminder is delivered. Required when adding one.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub method: Option<GcalEventReminderMethod>,
    /// How many minutes before the start of the event the reminder
    /// triggers, between 0 and 40320 (four weeks). Required when adding
    /// one.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub minutes: Option<u32>,
}

/// The resource an event was created from.
#[derive(Debug, Clone, Default, Deserialize, Serialize, Eq, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct GcalEventSource {
    /// URL of the source, whose scheme must be HTTP or HTTPS.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    /// Title of the source, such as the title of a web page or the
    /// subject of an email.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
}

/// The extended properties of an event.
#[derive(Debug, Clone, Default, Deserialize, Serialize, Eq, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct GcalEventExtendedProperties {
    /// Properties private to the copy of the event on this calendar.
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub private: BTreeMap<String, String>,
    /// Properties shared with the copies of the event on the attendees'
    /// calendars.
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub shared: BTreeMap<String, String>,
}

/// One file attached to an event.
#[derive(Debug, Clone, Default, Deserialize, Serialize, Eq, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct GcalEventAttachment {
    /// Id of the attached file, read-only. For a Google Drive file, the
    /// id of the matching Drive API resource.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub file_id: Option<String>,
    /// URL of the attachment. Required when adding one.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub file_url: Option<String>,
    /// Title of the attachment.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    /// Media type of the attachment.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub mime_type: Option<String>,
    /// URL of the icon of the attachment, modifiable on third-party
    /// attachments only.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub icon_link: Option<String>,
}

/// A gadget extending an event. Deprecated: the structure now only
/// carries birthday calendar metadata.
#[derive(Debug, Clone, Default, Deserialize, Serialize, Eq, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct GcalEventGadget {
    /// Type of the gadget.
    #[serde(default, rename = "type", skip_serializing_if = "Option::is_none")]
    pub gadget_type: Option<String>,
    /// Title of the gadget.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    /// URL of the gadget, whose scheme must be HTTPS.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub link: Option<String>,
    /// URL of the icon of the gadget, whose scheme must be HTTPS.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub icon_link: Option<String>,
    /// Width of the gadget in pixels.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub width: Option<u32>,
    /// Height of the gadget in pixels.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub height: Option<u32>,
    /// Display mode of the gadget.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub display: Option<String>,
    /// Preferences of the gadget.
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub preferences: BTreeMap<String, String>,
}

/// Birthday or special event data of an event.
#[derive(Debug, Clone, Default, Deserialize, Serialize, Eq, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct GcalEventBirthdayProperties {
    /// Type of birthday or special event. Only
    /// [`GcalEventBirthdayType::Birthday`] can be created; the type
    /// cannot change afterwards.
    #[serde(default, rename = "type", skip_serializing_if = "Option::is_none")]
    pub birthday_type: Option<GcalEventBirthdayType>,
    /// Custom label of the special date, set when the type is
    /// [`GcalEventBirthdayType::Custom`], read-only.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub custom_type_name: Option<String>,
    /// Resource name of the linked contact, of the form
    /// `people/c12345`, which the People API resolves. Read-only.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub contact: Option<String>,
}

/// Focus time data of an event.
#[derive(Debug, Clone, Default, Deserialize, Serialize, Eq, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct GcalEventFocusTimeProperties {
    /// Whether overlapping invitations are declined automatically.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub auto_decline_mode: Option<GcalEventAutoDeclineMode>,
    /// The status the user is marked with in Chat and related products.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub chat_status: Option<GcalEventChatStatus>,
    /// The message sent when an invitation is declined automatically.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub decline_message: Option<String>,
}

/// Out of office data of an event.
#[derive(Debug, Clone, Default, Deserialize, Serialize, Eq, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct GcalEventOutOfOfficeProperties {
    /// Whether overlapping invitations are declined automatically.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub auto_decline_mode: Option<GcalEventAutoDeclineMode>,
    /// The message sent when an invitation is declined automatically.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub decline_message: Option<String>,
}

/// Working location data of an event.
#[derive(Debug, Clone, Default, Deserialize, Serialize, Eq, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct GcalEventWorkingLocationProperties {
    /// Type of the working location. Required when adding working
    /// location properties, and the sub-field of the matching name
    /// carries the details.
    #[serde(default, rename = "type", skip_serializing_if = "Option::is_none")]
    pub working_location_type: Option<GcalEventWorkingLocationType>,
    /// Present, and typically empty, when the user works from home.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub home_office: Option<Value>,
    /// Present when the user works from an office.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub office_location: Option<GcalEventWorkingLocationOffice>,
    /// Present when the user works from a custom location.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub custom_location: Option<GcalEventWorkingLocationCustom>,
}

/// The office a user works from.
#[derive(Debug, Clone, Default, Deserialize, Serialize, Eq, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct GcalEventWorkingLocationOffice {
    /// Name of the office displayed in the Calendar clients.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    /// Identifier of the building, referring to the resources database
    /// of the organization.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub building_id: Option<String>,
    /// Identifier of the floor.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub floor_id: Option<String>,
    /// Identifier of the floor section.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub floor_section_id: Option<String>,
    /// Identifier of the desk.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub desk_id: Option<String>,
}

/// The custom location a user works from.
#[derive(Debug, Clone, Default, Deserialize, Serialize, Eq, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct GcalEventWorkingLocationCustom {
    /// Extra label describing the location.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
}

/// The conference attached to an event.
#[derive(Debug, Clone, Default, Deserialize, Serialize, Eq, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct GcalConferenceData {
    /// Id of the conference, for the client to track conferences with.
    /// Deprecated for display purposes.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub conference_id: Option<String>,
    /// The conference solution, such as Google Meet. Unset while a
    /// create request is pending or has failed.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub conference_solution: Option<GcalConferenceSolution>,
    /// The request generating a new conference for this event, resolved
    /// asynchronously by the server.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub create_request: Option<GcalCreateConferenceRequest>,
    /// The ways of joining the conference, all belonging to the same
    /// conference.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub entry_points: Vec<GcalEntryPoint>,
    /// Additional solution-specific settings, such as enabling video
    /// streaming.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub parameters: Option<GcalConferenceParameters>,
    /// Additional notes to display to the user, which may contain HTML.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
    /// Server-generated signature of the conference data. Unset while a
    /// create request is pending or has failed.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub signature: Option<String>,
}

/// The provider backing a conference.
#[derive(Debug, Clone, Default, Deserialize, Serialize, Eq, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct GcalConferenceSolution {
    /// The key uniquely identifying the solution.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub key: Option<GcalConferenceSolutionKey>,
    /// The user-visible name of the solution, not localized.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The user-visible icon of the solution.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub icon_uri: Option<String>,
}

/// The key uniquely identifying a conference solution.
#[derive(Debug, Clone, Default, Deserialize, Serialize, Eq, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct GcalConferenceSolutionKey {
    /// The type of the solution. A client meeting an unfamiliar or
    /// empty type should still display the entry points, but disallow
    /// modifications.
    #[serde(default, rename = "type", skip_serializing_if = "Option::is_none")]
    pub solution_type: Option<GcalConferenceSolutionType>,
}

/// A request to generate a new conference and attach it to an event.
#[derive(Debug, Clone, Default, Deserialize, Serialize, Eq, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct GcalCreateConferenceRequest {
    /// Client-generated unique id of the request, to be regenerated for
    /// every new request: reusing one replays the previous outcome.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub request_id: Option<String>,
    /// The conference solution to generate, such as Google Meet.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub conference_solution_key: Option<GcalConferenceSolutionKey>,
    /// The status of the request, read-only.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub status: Option<GcalConferenceRequestStatus>,
}

/// The status of a conference create request.
#[derive(Debug, Clone, Default, Deserialize, Serialize, Eq, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct GcalConferenceRequestStatus {
    /// The current status of the request, read-only.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub status_code: Option<GcalConferenceRequestStatusCode>,
}

/// One way of joining a conference.
#[derive(Debug, Clone, Default, Deserialize, Serialize, Eq, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct GcalEntryPoint {
    /// The type of the entry point.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub entry_point_type: Option<GcalEntryPointType>,
    /// The URI of the entry point: an HTTP or HTTPS URL for video, a
    /// `tel:` URI for phone, a `sip:` URI for SIP.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub uri: Option<String>,
    /// The user-visible label of the URI, not localized.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    /// The PIN needed to access the conference.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub pin: Option<String>,
    /// The access code needed to access the conference.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub access_code: Option<String>,
    /// The meeting code needed to access the conference.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub meeting_code: Option<String>,
    /// The passcode needed to access the conference.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub passcode: Option<String>,
    /// The password needed to access the conference.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub password: Option<String>,
    /// The CLDR/ISO 3166 region code of the country of a phone entry
    /// point, such as `SE` for Sweden.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub region_code: Option<String>,
    /// Features of the entry point, such as being toll or toll-free.
    /// The reference does not enumerate them, so they stay untyped.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub entry_point_features: Vec<String>,
}

/// Additional solution-specific settings of a conference.
#[derive(Debug, Clone, Default, Deserialize, Serialize, Eq, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct GcalConferenceParameters {
    /// The settings specific to a third-party conference provider.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub add_on_parameters: Option<GcalConferenceAddOnParameters>,
}

/// The settings specific to a third-party conference provider.
#[derive(Debug, Clone, Default, Deserialize, Serialize, Eq, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct GcalConferenceAddOnParameters {
    /// The opaque key/value settings of the provider.
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub parameters: BTreeMap<String, String>,
}

/// Status of an event.
#[derive(Debug, Clone, Copy, Deserialize, Serialize, Eq, PartialEq)]
#[serde(rename_all = "camelCase")]
pub enum GcalEventStatus {
    /// The event is confirmed. This is the default status.
    Confirmed,
    /// The event is tentatively confirmed.
    Tentative,
    /// The event is cancelled, meaning either a deleted event or, on a
    /// recurring series, an instance that should no longer be shown. A
    /// listing only returns cancelled events on an incremental sync or
    /// when deleted events are explicitly asked for.
    Cancelled,
}

/// Whether an event blocks time on the calendar.
#[derive(Debug, Clone, Copy, Deserialize, Serialize, Eq, PartialEq)]
#[serde(rename_all = "camelCase")]
pub enum GcalEventTransparency {
    /// The event blocks time, showing the user as busy. This is the
    /// default.
    Opaque,
    /// The event does not block time, leaving the user available.
    Transparent,
}

/// Visibility of an event.
#[derive(Debug, Clone, Copy, Deserialize, Serialize, Eq, PartialEq)]
#[serde(rename_all = "camelCase")]
pub enum GcalEventVisibility {
    /// The default visibility of the events of the calendar.
    Default,
    /// Every reader of the calendar sees the event details.
    Public,
    /// Only the attendees see the event details.
    Private,
    /// Same as private, kept for compatibility.
    Confidential,
}

/// Specific type of an event.
#[derive(Debug, Clone, Copy, Deserialize, Serialize, Eq, PartialEq)]
#[serde(rename_all = "camelCase")]
pub enum GcalEventType {
    /// An all-day event recurring every year.
    Birthday,
    /// A regular event, or one not further specified.
    Default,
    /// A focus-time event.
    FocusTime,
    /// An event coming from Gmail, which cannot be created.
    FromGmail,
    /// An out-of-office event.
    OutOfOffice,
    /// A working-location event.
    WorkingLocation,
}

/// The response of an attendee to an event invitation.
#[derive(Debug, Clone, Copy, Deserialize, Serialize, Eq, PartialEq)]
#[serde(rename_all = "camelCase")]
pub enum GcalEventAttendeeResponseStatus {
    /// The attendee has not responded yet, recommended for new events.
    NeedsAction,
    /// The attendee declined the invitation.
    Declined,
    /// The attendee tentatively accepted the invitation.
    Tentative,
    /// The attendee accepted the invitation.
    Accepted,
}

/// The asynchronous operation ongoing for an attendee.
#[derive(Debug, Clone, Copy, Deserialize, Serialize, Eq, PartialEq)]
#[serde(rename_all = "camelCase")]
pub enum GcalEventAttendeeAsyncOperation {
    /// The operation, such as listing the members of a large group, is
    /// still running.
    InProgress,
}

/// How a reminder is delivered.
#[derive(Debug, Clone, Copy, Deserialize, Serialize, Eq, PartialEq)]
#[serde(rename_all = "camelCase")]
pub enum GcalEventReminderMethod {
    /// The reminder is sent by email.
    Email,
    /// The reminder is shown as a UI popup.
    Popup,
}

/// Type of birthday or special event.
#[derive(Debug, Clone, Copy, Deserialize, Serialize, Eq, PartialEq)]
#[serde(rename_all = "camelCase")]
pub enum GcalEventBirthdayType {
    /// An anniversary other than a birthday, always linked to a
    /// contact.
    Anniversary,
    /// A birthday. This is the default, and the only type the API
    /// creates.
    Birthday,
    /// A special date whose label the custom type name carries, always
    /// linked to a contact.
    Custom,
    /// A special date in none of the other categories, always linked to
    /// a contact.
    Other,
    /// The calendar owner's own birthday, never linked to a contact.
    /// Serialized as `self`.
    #[serde(rename = "self")]
    Own,
}

/// Whether invitations overlapping a focus time or out of office event
/// are declined automatically.
#[derive(Debug, Clone, Copy, Deserialize, Serialize, Eq, PartialEq)]
#[serde(rename_all = "camelCase")]
pub enum GcalEventAutoDeclineMode {
    /// No invitation is declined.
    DeclineNone,
    /// Every conflicting invitation is declined, including the ones
    /// already accepted.
    DeclineAllConflictingInvitations,
    /// Only the conflicting invitations arriving while the event is
    /// present are declined.
    DeclineOnlyNewConflictingInvitations,
}

/// The status a focus time event marks the user with in Chat.
#[derive(Debug, Clone, Copy, Deserialize, Serialize, Eq, PartialEq)]
#[serde(rename_all = "camelCase")]
pub enum GcalEventChatStatus {
    /// The user stays available.
    Available,
    /// The user is marked as do not disturb.
    DoNotDisturb,
}

/// Type of the working location of an event.
#[derive(Debug, Clone, Copy, Deserialize, Serialize, Eq, PartialEq)]
#[serde(rename_all = "camelCase")]
pub enum GcalEventWorkingLocationType {
    /// The user works at home.
    HomeOffice,
    /// The user works from an office.
    OfficeLocation,
    /// The user works from a custom location.
    CustomLocation,
}

/// The current status of a conference create request.
#[derive(Debug, Clone, Copy, Deserialize, Serialize, Eq, PartialEq)]
#[serde(rename_all = "camelCase")]
pub enum GcalConferenceRequestStatusCode {
    /// The request is still being processed.
    Pending,
    /// The request succeeded and the entry points are populated.
    Success,
    /// The request failed and there is no entry point.
    Failure,
}

/// The type of a conference entry point.
#[derive(Debug, Clone, Copy, Deserialize, Serialize, Eq, PartialEq)]
#[serde(rename_all = "camelCase")]
pub enum GcalEntryPointType {
    /// Joining the conference over HTTP. A conference has at most one.
    Video,
    /// Joining the conference by dialing a phone number. A conference
    /// may have several.
    Phone,
    /// Joining the conference over SIP. A conference has at most one.
    Sip,
    /// Further joining instructions, such as additional phone numbers.
    /// A conference has at most one, and it is not valid on its own.
    More,
}

/// Who gets notified by email of an event change.
#[derive(Debug, Clone, Copy, Deserialize, Serialize, Eq, PartialEq)]
#[serde(rename_all = "camelCase")]
pub enum GcalSendUpdates {
    /// Every guest is notified.
    All,
    /// Only the guests outside the Google Calendar ecosystem are
    /// notified, so that they keep receiving iCalendar invitations.
    ExternalOnly,
    /// No guest is notified.
    None,
}
